spring:
  application:
    name: tlias-web-management

#配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 你的用户名
    password: 你的密码

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  OSS:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: tlias-web-management-heima
    region: cn-beijing
